#!/usr/bin/env bash
# Usage: manage addrecord DOMAIN SUBDOMAIN TYPE IP TTL IDENT
# Help: Add a record
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

manage-prepare || exit $?

if [ "$MYSQL_DB" = "" ] ; then
  echo ERROR: addrecord currently suppots only MySQL backend
  echo but MYSQL_DB env var is empty
  exit 1
fi

if [ $# -lt 6 ] ; then
  echo Usage: $0 DOMAIN SUBDOMAIN TYPE IP TTL IDENT
  echo NOT: $@
  exit 1
fi

DOMAINID=`/usr/bin/mysql $MYSQL_DB -N -B -r -e "SELECT id FROM domains WHERE name='$1'"` || exit $?

if [ "$DOMAINID" = "" ] || [ "$DOMAINID" = "0" ] ; then
  echo ERROR: Domain $1 not found
  exit 1
fi

/usr/bin/mysql $MYSQL_DB -e "REPLACE records SET domain_id='$DOMAINID', name='$2.$1', type='$3', content='$4', ttl='$5', ident='$6'" || exit $?

echo Record $2.$1 created: $4